spring:
  datasource:
    url: jdbc:mysql://localhost:3307/user_auth_db
    username: root
    password: ---
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: ovidiu

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
